<?php
$latest_date = Meeting::getLatestMeetingDate();
$datepicker = new StdClass;
$datepicker->year = explode('-', $latest_date)[0];
$datepicker->month = explode('-', $latest_date)[1];
$datepicker->events = array();
$terms = array();
foreach (Meeting::searchByYearMonth($datepicker->year, $datepicker->month) as $meeting) {
    $dates = json_decode($meeting->dates);
    foreach ($dates as $d) {
        if (strpos($d, sprintf("%04d-%02d-", $datepicker->year, $datepicker->month)) !== 0) {
            continue;
        }
        $datepicker->events[] = array($d, $meeting->getName(), '/meeting/show/' . $meeting->meeting_id);
    }
}
?>
<?= $this->partial('common/header.phtml', $this) ?>
<div class="row">
    <div class="col-sm">
        <?= $this->partial('common/datepicker.phtml', $datepicker) ?>
    </div>
    <div class="col-sm">
        <h3>本站資料概況</h3>
        <dl class="row">
            <dt class="col-sm-3">議案數</dt>
            <dd class="col-sm-9"><?= count(Bill::search(1)) ?></dt>

            <dt class="col-sm-3">最新議案日期</dt>
            <dd class="col-sm-9"><?= substr(Bill::search(1)->max('billno')->billno, 0, 7) ?></dt>

            <dt class="col-sm-3">議事日程數</dt>
            <dd class="col-sm-9"><?= count(Meeting::search(1)) ?></dt>

            <dt class="col-sm-3">最新議事日程</dt>
            <dd class="col-sm-9"><?= Meeting::getLatestMeetingDate() ?></dd>
        </dl>
    </div>
</div>
<?= $this->partial('common/footer.phtml', $this) ?>
