<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
<link href="/static/common.css" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<title></title>
</head>
<body class="<?= $this->escape($this->body_class) ?>">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">立法院資訊網</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">首頁</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="#">會議</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="#">議案</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="#">公報</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="#">法律</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="#">立法委員</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container-fluid">

